name = "iswebsiteup"
main = "src/index.ts"
compatibility_date = "2023-10-30"

[vars]
URL_TO_CHECK = 'https://pcdapension.nic.in/'
# BOT_TOKEN='telegram bot token'
# CHAT_ID='your telegram chat id'

# Cron Triggers
# Docs: https://developers.cloudflare.com/workers/platform/triggers/cron-triggers/
# Configuration: https://developers.cloudflare.com/workers/wrangler/configuration/#triggers
[triggers]
crons = ["*/30 2-16 * * *"] # * * * * * = run every 30 minute, except 2-16 UTC
